---
# tasks file for ansible-role-upgrade-all-packages

- name: Upgrade all packages in RedHat systems
  block:

    - name: upgrade all packages (RedHat)
      yum:
        name: '*'
        state: latest
      tags:
        - skip_ansible_lint

    - name: Make sure yum-utils is installed so we can use command "needs-restarting"
      yum:
        name: yum-utils
        state: present

    - name: Check if the machine needs a reboot
      command: needs-restarting -r
      ignore_errors: true
      changed_when: false
      register: needs_restarting_output

    - name: Reboot the machine if required
      reboot:
      when:
        - needs_restarting_output.rc != 0
        - not ansible_virtualization_type == "docker"       # skip reboot if this is a CI test in a container
        - not ansible_virtualization_type == "containerd"   # skip reboot if this is a CI test in a container

  when: ansible_os_family == "RedHat"


- name: Upgrade all packages in Debian systems
  block:

    - name: Install aptitude is this is a debian/ubuntu system
      apt:
        pkg: aptitude
        state: present

    - name: upgrade all packages (Debian)
      apt:
        name: '*'
        state: latest
      register: upgraded_packages
      tags:
        - skip_ansible_lint

    - name: Check if file /var/run/reboot-required exists
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot the machine if needed
      reboot:
      when:
        - reboot_required_file.exists
        - not ansible_virtualization_type == "docker"       # skip reboot if this is a CI test in a container
        - not ansible_virtualization_type == "containerd"   # skip reboot if this is a CI test in a container

  when: ansible_os_family == "Debian"
