---

name: "CI tests"

on:
  pull_request:
  push:
  release:
    types:
      - published

defaults:
  run:
    working-directory: 'ansible-role-upgrade-all-packages'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'ansible-role-upgrade-all-packages'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint ansible

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint .

  # release:
  #   name: Release to galaxy
  #   needs:
  #     - lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: galaxy
  #       uses: robertdebock/galaxy-action@1.2.1
  #       with:
  #         galaxy_api_key: ${{ secrets.galaxy_api_key }}
